-- ============================================================================
-- Fichier          : description_base_tournois.sql
-- Auteur           : PA BESSERO
-- Date             : Novembre 2017
-- Base				: tournois
-- Role             : Decrit la base TOURNOIS
-- Fichier resultat : descritpion_base_tournois.out
-- ============================================================================

PURGE RECYCLEBIN;

-- Edition de la taille des sorties
COL ctype FORMAT A5
COL cname FORMAT A15
COL ctable FORMAT A20
COL ccolumn FORMAT A20
COL rtable FORMAT A20
COL rname FORMAT A15
COL cond FORMAT A30


SPOOL description_base_surgeles.out

PROMPT 'Liste les attributs de la table EQUIPE'

DESC EQUIPE;

PROMPT 'Liste les cles primaires et uniques de la table EQUIPE'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE IN ('P' , 'U')
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'EQUIPE';


PROMPT 'Liste les cles etrangeres de la relation EQUIPE'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as CNAME, CC.COLUMN_NAME as ccolumn, R.TABLE_NAME as rtable, R.COLUMN_NAME as rname
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC, USER_CONS_COLUMNS R
WHERE C.CONSTRAINT_TYPE = 'R'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'EQUIPE'
AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME;

PROMPT 'Liste les contraintes de CHECK de la table EQUIPE'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, C.SEARCH_CONDITION as cond, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE = 'C'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'EQUIPE';
SPOOL OFF


PROMPT 'Liste les attributs de la table JOUEUR'

DESC JOUEUR;

PROMPT 'Liste les cles primaires et uniques de la table JOUEUR'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE IN ('P' , 'U')
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'JOUEUR';


PROMPT 'Liste les cles etrangeres de la relation JOUEUR'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as CNAME, CC.COLUMN_NAME as ccolumn, R.TABLE_NAME as rtable, R.COLUMN_NAME as rname
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC, USER_CONS_COLUMNS R
WHERE C.CONSTRAINT_TYPE = 'R'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'JOUEUR'
AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME;

PROMPT 'Liste les contraintes de CHECK de la table JOUEUR'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, C.SEARCH_CONDITION as cond, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE = 'C'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'JOUEUR';
SPOOL OFF

PROMPT 'Liste les attributs de la table MATCH'

DESC MATCH;

PROMPT 'Liste les cles primaires et uniques de la table MATCH'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE IN ('P' , 'U')
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'MATCH';


PROMPT 'Liste les cles etrangeres de la relation MATCH'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as CNAME, CC.COLUMN_NAME as ccolumn, R.TABLE_NAME as rtable, R.COLUMN_NAME as rname
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC, USER_CONS_COLUMNS R
WHERE C.CONSTRAINT_TYPE = 'R'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'MATCH'
AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME;

PROMPT 'Liste les contraintes de CHECK de la table MATCH'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, C.SEARCH_CONDITION as cond, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE = 'C'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'MATCH';
SPOOL OFF

PROMPT 'Liste les attributs de la table COMPOSITION'

DESC COMPOSITION;

PROMPT 'Liste les cles primaires et uniques de la table COMPOSITION'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE IN ('P' , 'U')
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'COMPOSITION';


PROMPT 'Liste les cles etrangeres de la relation COMPOSITION'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as CNAME, CC.COLUMN_NAME as ccolumn, R.TABLE_NAME as rtable, R.COLUMN_NAME as rname
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC, USER_CONS_COLUMNS R
WHERE C.CONSTRAINT_TYPE = 'R'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'COMPOSITION'
AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME;

PROMPT 'Liste les contraintes de CHECK de la table COMPOSITION'

SELECT C.CONSTRAINT_TYPE as ctype, C.CONSTRAINT_NAME as cname, C.SEARCH_CONDITION as cond, CC.COLUMN_NAME as ccolumn
FROM USER_CONSTRAINTS C, USER_CONS_COLUMNS CC
WHERE C.CONSTRAINT_TYPE = 'C'
AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
AND C.TABLE_NAME = CC.TABLE_NAME
AND C.TABLE_NAME = 'COMPOSITION';
SPOOL OFF
